use_frameworks!

platform :ios, '9.0'

target 'htTool_Example' do
  pod 'htTool', :path => '../'

  target 'htTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
